package com.arielpertile.boxWeb.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * Fight generated by hbm2java
 */
public class Fight{

	@Id
	@Column(name = "FightID")
	private Integer fightId;
	
	@Column(name = "CityID")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cityId")
	private City city;
	
	@Column(name = "ResultID")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resultId")
	private Result result;
	
	@Column(name = "BoxerID1")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "boxerId")
	private Boxer boxerId1;
	
	@Column(name = "BoxerID2")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "boxerId")
	private Boxer boxerId2;
	
	@Column(name = "DivisionID")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "divisionId")
	private Division division;
	
	@Column(name = "WinnerID")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "boxerId")
	private Boxer winnerId;
	
	@Column(name = "Date")
	private Date date;
	
	@Column(name = "Comment")
	private String comment;
	
	@Column(name = "FinalRound")
	private Integer finalRound;
	
	@Column(name = "FinalTime")
	private Date finalTime;
	
	@Column(name = "ScheduledRounds")
	private Integer scheduledRounds;	
	
	@OneToOne(mappedBy="fight")
	private TitleFight titleFight;

}
